# Generated by Django 2.2 on 2019-04-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
