# Generated by Django 2.2 on 2019-04-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_remove_photo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='idRoom',
        ),
        migrations.AddField(
            model_name='photo',
            name='idRoom',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
    ]
