# Generated by Django 2.2 on 2019-04-27 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20190427_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='idRoom',
        ),
        migrations.AddField(
            model_name='photo',
            name='idRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
    ]
