# Generated by Django 2.2 on 2019-04-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20190427_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='idRoom',
        ),
    ]
