# Generated by Django 2.1.7 on 2019-04-28 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_photo_idroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomConv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='convenience',
            name='idRoom',
        ),
        migrations.AddField(
            model_name='roomconv',
            name='convenience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Convenience'),
        ),
        migrations.AddField(
            model_name='roomconv',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoomConv', to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='roomconv',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='convenience',
            name='rooms',
            field=models.ManyToManyField(through='rooms.RoomConv', to='rooms.Room'),
        ),
    ]
