# Generated by Django 2.1.7 on 2019-04-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20190428_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('person', models.IntegerField()),
            ],
        ),
    ]
