# Generated by Django 2.1.7 on 2019-04-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20190429_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
